version: '3.4'

services:
  appointmentscheduler.server:
    image: ${DOCKER_REGISTRY-}appointmentschedulerserver
    build:
      context: .
      dockerfile: AppointmentScheduler/AppointmentScheduler.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/.aspnet/https/aspnetapp.pfx
  appointmentscheduler.client:
    image: appointmentscheduler.client:1.0
